site_name: Minio K8S buckets operator
theme:
  language: en
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://gitea.communiquons.org/pierre/MinioK8sBuckets
edit_uri: src/branch/master/docs/

plugins:
  - search
