apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: minio-buckets
  namespace: default
  labels:
    app: minio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-buckets
  namespace: default
rules:
- apiGroups: ["communiquons.org"]
  resources: ["minioinstances", "miniobuckets"]
  verbs: ["get", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minio-buckets
  namespace: default
subjects:
- kind: ServiceAccount
  name: minio-buckets
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minio-buckets
